// ==========================================================================
// 📖 课文与字词矩阵数据（按词组单位：全拼音与双语翻译无死角覆盖） - data.js
// ==========================================================================

const lessonTitle = "珍珠鸟";

const lessonData = [
    // --- 第1段 ---
    ["三个月前，", "sān gè yuè qián", "three months ago", "tiga bulan yang lalu"],
    ["朋友", "péng you", "friend", "kawan / sahabat"],
    ["送我", "sòng wǒ", "gave me as a gift", "hadiahkan kepada saya"],
    ["一对", "yí duì", "a pair of", "sepasang"],
    ["珍珠鸟。", "zhēn zhū niǎo", "zebra finches / pearl birds", "burung mutiara / burung pipit zebra"],
    ["这是一种", "zhè shì yì zhǒng", "this is a kind of", "ini merupakan sejenis"],
    ["怕人的", "pà rén de", "timid / afraid of humans", "yang takut akan manusia / liar"],
    ["鸟，", "niǎo", "bird", "burung"],
    ["红嘴红脚，", "hóng zuǐ hóng jiǎo", "red beak and red feet", "paruh merah dan kaki merah"],
    ["灰蓝色的", "huī lán sè de", "greyish blue", "yang berwarna biru kelabu"],
    ["毛，", "máo", "feathers / fur", "bulu"],
    ["后背儿", "hòu bèi r", "the back", "bahagian belakang badan"],
    ["还生着", "hái shēng zhe", "also growing / bearing", "bahkan ditumbuhi"],
    ["珍珠似的", "zhēn zhū sì de", "pearl-like", "seumpama mutiara"],
    ["白点。", "bái diǎn", "white spots", "bintik-bintik putih"],
    ["我把它", "wǒ bǎ tā", "I take it (object marker)", "saya membiarkannya (penanda objek)"],
    ["安放在", "ān fàng zài", "placed in / settled at", "menempatkannya di"],
    ["一个", "yí gè", "a", "sebuah"],
    ["简陋的", "jiǎn lòu de", "simple and crude / shabby", "daif / ringkas / buruk"],
    ["竹条编织的", "zhú tiáo biān zhī de", "woven from bamboo strips", "yang dianyam daripada bilah bambu"],
    ["鸟笼里，", "niǎo lóng lǐ", "inside the birdcage", "di dalam sangkar burung"],
    ["挂在", "guà zài", "hanging on", "digantung di"],
    ["窗前。", "chuāng qián", "in front of the window", "hadapan tingkap"],
    ["我还在", "wǒ hái zài", "I also at", "saya juga di"],
    ["笼子周围", "lóng zi zhōu wéi", "around the cage", "sekeliling sangkar"],
    ["随意插上", "suí yì chā shàng", "randomly inserted / casually set", "secara sesuka hati mencucuk naik"],
    ["几支", "jǐ zhī", "several (branches)", "beberapa tangkai"],
    ["生生不息的", "shēng shēng bù xī de", "endless / endless life growth", "yang tumbuh subur tanpa henti / malar hijau"],
    ["垂蔓，", "chuí màn", "hanging vines", "daun menjalar / akar yang bergantungan"],
    ["那浓浓的", "nà nóng nóng de", "those thick / dense", "yang pekat / lebat itu"],
    ["绿叶，", "lǜ yè", "green leaves", "daun hijau"],
    ["宛如", "wǎn rú", "just like / as if", "umpama / seolah-olah"],
    ["一堵", "yì dǔ", "a (classifier for walls)", "sebuah"],
    ["无形的", "wú xíng de", "invisible / intangible", "yang ghaib / tidak kelihatan"],
    ["墙，", "qiáng", "wall", "tembok / dinding"],
    ["把鸟笼", "bǎ niǎo lóng", "the birdcage (object marker)", "sangkar burung (penanda objek)"],
    ["安全地", "ān quán dì", "safely", "dengan selamat"],
    ["包裹了", "bāo guǒ le", "wrapped up / enclosed", "menyelubungi / membungkus"],
    ["起来。", "qǐ lái", "up", "semula"],
    ["这样，", "zhè yàng", "in this way", "dengan sedemikian"],
    ["它们就", "tā men jiù", "they then", "mereka pun"],
    ["像住在", "xiàng zhù zài", "like living in", "seperti tinggal di"],
    ["深山密林里", "shēn shān mì lín lǐ", "deep mountains and dense forests", "dalam hutan rimba dan gunung dalam"],
    ["一样，", "yí yàng", "the same / just like", "sedemikian"],
    ["有了一种", "yǒu le yì zhǒng", "had a kind of", "mempunyai sejenis"],
    ["说不出的", "shuō bù chū lái de", "unspeakable / indescribable", "yang tidak dapat diungkapkan"],
    ["宽慰。", "kuān wèi", "consolation / relief / comfort", "kelegaan / ketenangan hati."],
    ["\n", "", "", ""],

    // --- 第2段 ---
    ["起初，", "qǐ chū", "at first / originally", "pada mulanya / asalnya"],
    ["它们确实", "tā men què shí", "they indeed", "mereka sememangnya"],
    ["惊得", "jīng de", "so shocked / frightened that", "terkejut sehinggakan"],
    ["魂飞魄散，", "hún fēi pò sàn", "frightened out of wits / terrified", "terperanjat besar / ketakutan setengah mati"],
    ["只敢躲在", "zhǐ gǎn duǒ zài", "only dare to hide behind", "hanya berani bersembunyi di belakang"],
    ["垂蔓后面。", "chuí màn hòu miàn", "behind the hanging vines", "belakang daun menjalar"],
    ["每当", "měi dāng", "whenever", "setiap kali"],
    ["有人走近，", "yǒu rén zǒu jìn", "someone walks near", "ada orang mendekati"],
    ["它们便", "tā men biàn", "they then", "mereka pun"],
    ["吓得", "xià de", "scared until", "ketakutan sehinggakan"],
    ["嗫嚅般", "niè rú bān", "mumbly / hesitatingly (here: low chirping)", "teragap-agap seakan-akan / cicit segan"],
    ["尖叫，", "jiān jiào", "screamed / chirped loudly", "menjerit / mencicit kuat"],
    ["在笼里", "zài lóng lǐ", "inside the cage", "di dalam sangkar"],
    ["跌跌撞撞地", "dié dié zhuàng zhuàng dì", "stumbling / tumbling", "teraba-raba / terhantuk-hantuk"],
    ["乱扑。", "luàn pū", "fluttering wildly / flapping frantically", "mengepak sayap dengan meluru liar"],
    ["我不去", "wǒ bú qù", "I do not go to", "saya tidak pergi"],
    ["打扰它们，", "dǎ rǎo tā men", "disturb them / bother them", "mengganggu mereka"],
    ["隔个", "gé gè", "separated by / every interval of", "selang"],
    ["一天两天，", "yì tiān liǎng tiān", "a day or two", "sehari dua"],
    ["只是", "zhǐ shì", "only / merely", "hanyalah / cuma"],
    ["默默地", "mò mò dì", "silently / quietly", "secara senyap / membisu"],
    ["添些", "tiān xiē", "add some", "menambah sikit"],
    ["鸟食", "niǎo shí", "bird food", "makanan burung"],
    ["和", "hé", "and", "dan"],
    ["换水。", "huàn shuǐ", "change water", "menukar air."],
    ["渐渐地，", "jiàn jiàn dì", "gradually", "beransur-ansur / lama-kelamaan"],
    ["它们的", "tā men de", "their", "mereka punya"],
    ["胆子大了，", "dǎn zi dà le", "courage grew bigger / became braver", "keberanian menjadi besar"],
    ["竟敢探出", "jìng gǎn tàn chū", "unexpectedly dare to poke out", "bahkan berani menjenguk keluar"],
    ["小脑袋来", "xiǎo nǎo dài lái", "little head", "kepala kecil untuk"],
    ["打量我。", "dǎ liang wǒ", "measure me up / size me up / observe me", "memerhatikan saya / meneliti."],
    ["\n", "", "", ""],

    // --- 第3段 ---
    ["过了不久，", "guò le bù jiǔ", "not long after", "tidak lama selepas itu"],
    ["那浓密的", "nà nóng mì de", "those thick / dense", "yang lebat / rimbun itu"],
    ["绿叶中", "lǜ yè zhōng", "among the green leaves", "di celahan daun hijau"],
    ["突然传出", "tū rán chuán chū", "suddenly came out", "tiba-tiba kedengaran keluar"],
    ["一声", "yì shēng", "a (sound of)", "sepotong bunyi"],
    ["娇嫩的", "jiāo nèn de", "tender / delicate / crisp", "yang comel / merdu / siul manja"],
    ["啼叫。", "tí jiào", "chirping / crowing / twittering", "siulan / cicitan burung."],
    ["细细看去，", "xì xì kàn qù", "looking closely", "melihat dengan teliti"],
    ["啊，", "ā", "ah", "ah / wah"],
    ["竟然", "jìng rán", "unexpectedly / to one's surprise", "rupa-rupanya / tidak disangka"],
    ["孵出了", "fū chū le", "hatched", "menetas keluar"],
    ["一只", "yì zhī", "a (classifier for birds)", "seekor"],
    ["小珍珠鸟！", "xiǎo zhēn zhū niǎo", "little pearl bird", "anak burung mutiara!"],
    ["\n", "", "", ""],

    // --- 第4段 ---
    ["这个", "zhè gè", "this", "budak/haiwan... ini"],
    ["小家伙", "xiǎo jiā huo", "little fellow / little guy", "si kecil / makhluk kecil ini"],
    ["极其", "jí qí", "extremely", "amat / sangat"],
    ["滑稽", "huá jī", "funny / comical", "lucu / melucukan"],
    ["可爱，", "kě ài", "lovely / cute", "comel"],
    ["身体", "shēn tǐ", "body", "tubuh badan"],
    ["卑微得", "bēi wēi de", "humble / tiny / insignificant until", "kerdil/kecil sehinggakan"],
    ["像个", "xiàng gè", "like a", "seperti sebuah"],
    ["毛茸茸的", "máo róng róng de", "fluffy / furry / downy", "yang berbulu lembut / gebu"],
    ["小球。", "xiǎo qiú", "small ball", "bola kecil."],
    ["它起初", "tā qǐ chū", "it at first", "ia pada mulanya"],
    ["只在", "zhǐ zài", "only at", "hanya di"],
    ["笼子周围", "lóng zi zhōu wéi", "around the cage", "sekeliling sangkar"],
    ["活动，", "huó dòng", "move around / exercise", "bergerak-gerak / beraktiviti"],
    ["随后，", "suí hòu", "afterwards / subsequently", "kemudian / selepas itu"],
    ["欲望", "yù wàng", "desire / curiosity", "keinginan / naluri rasa ingin tahu"],
    ["像杂草一样", "xiàng zá cǎo yí yàng", "like weeds", "seperti rumput liar / rumpai"],
    ["滋生，", "zī shēng", "grow multiply / grow wildly", "membiak / tumbuh meluap"],
    ["胆子", "dǎn zi", "courage / guts", "keberanian"],
    ["越来越大，", "yuè lái yuè dà", "getting bigger and bigger", "semakin hari semakin besar"],
    ["竟飞出了", "jìng fēi chū le", "unexpectedly flew out of", "bahkan terbang keluar dari"],
    ["鸟笼，", "niǎo lóng", "birdcage", "sangkar burung"],
    ["在我的", "wǒ de", "on my", "di atas saya punya"],
    ["写字台周围", "xiě zì tái zhōu wéi", "around the writing desk", "sekeliling meja tulis / meja kerja"],
    ["溜达。", "liū da", "stroll / wander around / loiter", "bersiar-siar / berjalan-jalan melompat."],
    ["它一会儿", "tā yī huì r", "it for a moment", "ia sekejap"],
    ["落在", "luò zài", "landed on / perched on", "hinggap di atas"],
    ["我的", "wǒ de", "my", "saya punya"],
    ["小杂货店般的", "xiǎo zá huò diàn bān de", "small grocery shop-like (stuffed packed)", "seperti kedai runcit kecil punya (penuh padat)"],
    ["书架上，", "shū jià shàng", "on the bookshelf", "atas rak buku"],
    ["挨次", "āi cì", "in turn / sequentially", "mengikut giliran / satu demi satu"],
    ["从每个", "cóng měi gè", "from every", "daripada setiap"],
    ["格子里", "gé zi lǐ", "inside the grid / shelf slot", "petak rak laci lǐ"],
    ["舀出", "yǎo chū", "scoop out (here: pull out/peep)", "mencedok keluar / menarik keluar"],
    ["几本书看；", "jǐ běn shū kàn", "several books to look", "beberapa buah buku untuk dilihat;"],
    ["一会儿", "yī huì r", "for a moment", "sekejap lagi"],
    ["蹦到", "bèng dào", "hopped to / jumped onto", "melompat ke atas"],
    ["我的", "wǒ de", "my", "saya punya"],
    ["茶杯旁，", "chá bēi páng", "beside the teacup", "sebelah cawan teh"],
    ["大口大口地", "dà kǒu dà kǒu dì", "in big mouthfuls", "dengan suapan besar / hirupan banyak"],
    ["啜着", "chuò zhe", "sipping", "menghirup / meminum sedikit-sedikit"],
    ["茶水。", "chá shuǐ", "tea / tea water", "air teh."],
    ["这时候，", "zhè shí hou", "at this time", "pada waktu ini"],
    ["我始终", "wǒ shǐ zhōng", "I from beginning to end / always", "saya sentiasa"],
    ["坐在", "zuò zài", "sitting at", "duduk di"],
    ["炉子后面", "lú zi hòu miàn", "behind the stove (desk area)", "belakang relau / sudut dapur"],
    ["平静地", "píng jìn dì", "peacefully / calmly", "dengan tenang / aman"],
    ["写作，", "xiě zuò", "writing", "menulis / mengarang"],
    ["没有", "méi yǒu", "did not", "tidak ada"],
    ["伸手", "shēn shǒu", "stretch out hand", "menghulurkan tangan"],
    ["去捉它。", "qù zhuō tā", "to catch it", "untuk menangkapnya."],
    ["好在", "hǎo zài", "fortunately / luckily", "mujur / nasib baik"],
    ["这一切，", "zhè yī qiè", "all of this", "semua ini"],
    ["让它", "ràng tā", "made it", "membiarkannya"],
    ["察觉到了", "chá jué dào le", "perceived / noticed", "menyedari / mengesan"],
    ["我的", "wǒ de", "my", "saya punya"],
    ["友善。", "yǒu shàn", "friendliness / kindness", "sifat baik hati / kebaikan."],
    ["\n", "", "", ""],

    // --- 第5段 ---
    ["有一天，", "yǒu yī tiān", "one day", "pada suatu hari"],
    ["它居然", "tā jū rán", "it unexpectedly / actually", "ia tidak disangka / malah"],
    ["飞到了", "fēi dào le", "flew to", "terbang ke"],
    ["我的", "wǒ de", "my", "saya punya"],
    ["笔尖旁。", "bǐ jiān páng", "beside the pen tip", "sebelah mata pena / hujung pen"],
    ["我", "wǒ", "I", "saya"],
    ["放慢了", "fàng màn le", "slowed down", "memperlahankan"],
    ["呼吸，", "hū xī", "breathing / breath", "nafas / pernafasan"],
    ["不经意地", "bù jīng yì dì", "inadvertently / carelessly / casually", "secara tidak sengaja / bersahaja"],
    ["转头", "zhuǎn tóu", "turn head", "menoleh kepala"],
    ["看它。", "kàn tā", "look at it", "memandangnya."],
    ["它有些", "tā yǒu xiē", "it somewhat", "ia agak sikit"],
    ["局促地", "jú cù dì", "uneasily / awkwardly (here: text adaptation style)", "canggung / gelisah (gaya adaptasi)"],
    ["笑了笑般地", "xiào le xiào bān dì", "as if smiling", "seolah-olah tersenyum"],
    ["跳动着，", "tiào dòng zhe", "hopping / jumping", "melompat-lompat"],
    ["歪着头", "wāi zhe tóu", "tilting head / cocking head", "telengkan kepala / sengetkan kepala"],
    ["注视着我。", "zhù shì zhe wǒ", "gazing at me", "menatap / merenung saya."],
    ["它看着看着，", "tā kàn zhe kàn zhe", "it looked and looked", "ia melihat demi melihat"],
    ["见我", "jiàn wǒ", "seeing me", "melihat saya"],
    ["完全没有", "wán quán méi yǒu", "completely did not", "sama sekali tidak ada"],
    ["妄动", "wàng dòng", "rash action / hostile movement", "bertindak liar / meluru kasar"],
    ["和", "hé", "and", "dan"],
    ["鄙夷，", "bǐ yí", "disdain / contempt / hostility", "pandangan hina / jijik / rengsa"],
    ["便", "biàn", "then", "lalu / maka"],
    ["大胆地", "dà dǎn dì", "boldly / daringly", "dengan berani"],
    ["跳到了", "tiào dào le", "hopped onto", "melompat ke atas"],
    ["我的", "wǒ de", "my", "saya punya"],
    ["手背上，", "shǒu bèi shàng", "on the back of hand", "atas belakang tangan"],
    ["用那双", "yòng nà shuāng", "using that pair of", "menggunakan sepasang... itu"],
    ["凹陷下去般", "āo xiàn xià qù bān", "sunken-like (here: text adaptation variant)", "cengkung (gaya variasi teks)"],
    ["亮堂的", "liàng táng de", "bright / luminous", "yang cerah / bersinar punya"],
    ["小眼睛", "xiǎo yǎn jing", "little eyes", "mata kecil"],
    ["看着我，", "kàn zhe wǒ", "looking at me", "memandang saya"],
    ["用红嘴", "yòng hóng zuǐ", "using red beak", "menggunakan paruh merah"],
    ["轻轻地", "qīng qīng dì", "gently", "dengan perlahan-lahan"],
    ["啄着", "zhuó zhe", "pecking", "mematuk-matuk"],
    ["我的", "wǒ de", "my", "saya punya"],
    ["手指。", "shǒu zhǐ", "finger", "jari-jemari."],
    ["\n", "", "", ""],

    // --- 第6段 ---
    ["就在这时，", "jiù zài zhè shí", "right at this moment", "tepat pada waktu ini"],
    ["屋里的", "wū lǐ de", "inside the room", "di dalam rumah punya"],
    ["尘嚣", "chén xiāo", "hubbub / noise of the world", "hiruk-pikuk / kekotoran"],
    ["尽散，", "jìn sàn", "all dissipated / cleared", "kesemuanya hilang / bersurai"],
    ["我的", "wǒ de", "my", "saya punya"],
    ["心", "xīn", "heart", "jantung / hati"],
    ["久久", "jiǔ jiǔ", "for a long time", "lama sekali"],
    ["无法", "wú fǎ", "unable to / cannot", "tidak mampu / tidak boleh"],
    ["平静。", "píng jìn", "calm down", "berasa tenang semula."],
    ["窗外，", "chuāng wài", "outside the window", "di luar tingkap"],
    ["那暗香袭人的", "àn xiāng xí rén de", "the fragrance-assailing", "haruman yang menusuk kalbu punya"],
    ["花丛中", "huā cóng zhōng", "among the flowers", "celahan semak bunga"],
    ["正映着", "zhèng yìng zhe", "reflecting / shining right now", "sedang memancarkan riak"],
    ["绚丽的", "xuàn lì de", "gorgeous / magnificent / brilliant", "yang indah berwarna-warni / gemilang"],
    ["黄昏。", "huáng hūn", "dusk / sunset / twilight", "waktu senja."],
    ["小家伙", "xiǎo jiā huo", "little fellow", "si kecil itu"],
    ["玩得", "wán de", "played until", "bermain sehinggakan"],
    ["有些", "yǒu xiē", "somewhat / a bit", "agak / sedikit"],
    ["疲惫了，", "pí bèi le", "exhausted / tired", "letih / lesu"],
    ["它居然", "tā jū rān", "it unexpectedly", "ia tidak disangka / malah"],
    ["一步地", "yí bù dì", "step by step (here: text variant closer)", "setapak demi setapak (rapat)"],
    ["挪在", "nuó zài", "moved onto / shifted to", "beralih di atas"],
    ["我的", "wǒ de", "my", "saya punya"],
    ["肩头，", "jiān tóu", "shoulder", "bahu / pundak"],
    ["小脑袋", "xiǎo nǎo dài", "little head", "kepala kecil"],
    ["一歪，", "yì wāi", "tilted", "meneleng sikit"],
    ["紧裹着", "jǐn guǒ zhe", "tightly wrapped in", "membungkus rapat"],
    ["它那", "tā nà", "its that", "ia punya... itu"],
    ["灰蓝色的", "huī lán sè de", "greyish blue", "berwarna biru kelabu punya"],
    ["羽毛，", "yǔ máo", "feathers", "bulu pelepah"],
    ["竟然", "jìng rán", "unexpectedly", "rupa-rupanya / tidak disangka"],
    ["甜甜地", "tián tián dì", "sweetly", "dengan manisnya"],
    ["睡着了。", "shuì zháo le", "fell asleep", "tertidur."],
    ["\n", "", "", ""],

    // --- 第7段 ---
    ["看着", "kàn zhe", "looking at", "memandang"],
    ["手中", "shǒu zhōng", "in the hand", "di dalam tangan"],
    ["那支", "zhè zhī", "that (classifier for pens)", "sebatang... itu"],
    ["停了笔的", "tíng le bǐ de", "stopped writing / paused pen", "yang berhenti menulis punya"],
    ["钢笔，", "gāng bǐ", "fountain pen / pen", "pena / pen dakwat"],
    ["再看着", "zài kàn kàn", "looking again at", "melihat sekali lagi ke arah"],
    ["肩头", "jiān tóu", "shoulder", "bahu"],
    ["小鸟", "niǎo", "little bird", "burung kecil punya"],
    ["满足、", "mǎn zú", "satisfied / content", "kepuasan"],
    ["豁达的", "huò dá de", "open-minded / relaxed / carefree", "berlapang dada / tenang punya"],
    ["睡姿，", "shuì zī", "sleeping posture", "gaya tidur / posisi tidur"],
    ["我的", "wǒ de", "my", "saya punya"],
    ["泪水", "lèi shuǐ", "tears", "air mata"],
    ["无声无息地", "wú shēng wú xī dì", "silently / without a sound", "tanpa sebarang bunyi"],
    ["淌下来。", "tǎng xià lái", "streamed down / trickled", "mengalir turun."],
    ["\n", "", "", ""],

    // --- 第8段 ---
    ["纯洁的", "chún jié de", "pure / clean", "yang suci / bersih"],
    ["思想，", "sī xiǎng", "thoughts / mind", "pemikiran / minda"],
    ["可使", "kě shǐ", "can make", "boleh menyebabkan"],
    ["微小的", "wēi xiǎo de", "tiny / small", "perbuatan kecil"],
    ["行动", "xíng dòng", "action / deed", "tindakan / amalan"],
    ["变得", "biàn de", "become", "menjadi"],
    ["高贵。", "gāo guì", "noble / lofty", "mulia / luhur."],
    ["善良", "shàn liáng", "kindness / goodness", "kebaikan / ketulusan"],
    ["从来不是", "cóng lái bú  shì", "has never been", "semenjak awal bukanlah"],
    ["高高在上的", "gāo gāo zài shàng de", "condescending / high and mighty", "berada tinggi di atas / angkuh / sombong"],
    ["教训", "jiào xùn", "lecture / scolding / lesson", "leteran / pengajaran"],
    ["和", "hé", "and", "dan"],
    ["施舍，", "shī shě", "alms / charity", "sedekah / belas iksan"],
    ["而是给", "ér shì gěi", "but rather to give", "tetapi melainkan memberi"],
    ["弱小生命", "ruò xiǎo shēng mìng", "weak and small life / tiny life", "nyawa makhluk yang lemah dan kecil"],
    ["以最大的", "yǐ zuì dà de", "with the greatest", "dengan... yang paling besar"],
    ["尊重", "zūn zhòng", "respect", "penghormatan / menghormati"],
    ["与", "yǔ", "and", "dan"],
    ["自由。", "zì yóu", "freedom / liberty", "kebebasan."],
    ["信赖，", "xìn lài", "trust / reliance / faith", "kepercayaan / keyakinan / amanah"],
    ["往往", "wǎng wǎng", "often / frequently", "sentiasa / kerap kali"],
    ["创造出", "chuàng zào chū", "create / generate", "menciptakan / melahirkan"],
    ["美好的", "měi hǎo de", "beautiful / wonderful", "yang murni / indah"],
    ["境界。", "jìng jiè", "realm / boundary / state", "keadaan / tahap / sempadan pemikiran."],
    ["\n", "", "", ""],

    // --- 作者落款 ---
    ["（冯骥才《珍珠鸟》，有改动）", "", "", ""]
];
